# -------------------------------------------
# Version of the docker-compose file
version: '3.3'

# -------------------------------------------
# Services of the docker-compose file
services:

  # Service for the database
  db-svc:
    container_name: db-svc
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      NAME_DB: ${NAME_DB}
      USER_DB: ${USER_DB}
      PASS_DB: ${PASS_DB}
