# File: compose.yml
# Description: This file contains the services that will be used in the project.

#------------------------------------------
# Services of the docker-compose file
services:

  #----------------------------------------
  # Define back-end services
  #----------------------------------------

  # Define users ms service
  users-ms-svc:
    container_name: users-ms-svc
    build: users-ms
    ports:
      - "7071:8080"
    
  # Define task ms service
  tasks-ms-svc:
    container_name: tasks-ms-svc
    build: tasks-ms
    ports:
      - "7072:8080"
    
  # Define reports ms service
  reports-ms-svc:
    container_name: reports-ms-svc
    build: reports-ms
    ports:
      - "7073:8080"